default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean")
    gradle(task: "test")
  end

  desc "Submit a new Build to Crashlytics Alpha Channel"
  lane :alpha do
    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
      gradle_file: "app/build.gradle"
    )

    increment_version_code(
        gradle_file_path: "app/build.gradle"
    )

    gradle(task: "clean")

    gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
          "android.buildTypes.release.storeFile" => ENV["UPLOAD_STORE_PATH"],
          "android.buildTypes.release.storePassword" => ENV["UPLOAD_STORE_PASSWORD"],
          "android.buildTypes.release.keyAlias" => ENV["UPLOAD_KEY_ALIAS"],
          "android.buildTypes.release.keyPassword" => ENV["UPLOAD_KEY_PASSWORD"],
        }
    )
    
    supply(
        track: "alpha",
        apk: "android/app/build/outputs/apk/release/app-release.apk"
    )
  end
end
