# version 1.0
# add npm ci
name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: install
        run: yarn install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: update
        run: bundle update
        working-directory: android 
      
      - name: test
        run: bundle exec fastlane test
        working-directory: android
